/**
 * Converts date generated by js in to epoch time to give to API
 * 
 * @param {int} dateIn epoch time in milliseconds
 * @returns {int} epoch time in seconds
 */
function dateToEpoch(dateIn) {
	var date = new Date(dateIn).getTime() / 1000;
	return date;
}

/**
 * Takes information given in add food form on addFood.html and creates a JSON to send to API
 * 
 */
function submitFood() {
    var form = document.getElementById("addFoodForm");
    alert(form);
    var json =  "{";

    // Loops through each input box in form.
    for (var i=0; i < form.length; i++) {
    	if (form.elements[i].id != "sub") { // Ignores submission button when adding information to JSON.
    		json += '"' + form.elements[i].id + '":';
    		if (form.elements[i].id == "expiryDate") {
              if (isNaN(dateToEpoch(form.elements[i].value))) { // If user doesn't enter expiry date, changes NaN to null.
                json += 'null';
              } else {
    			json += '' + dateToEpoch(form.elements[i].value) + ',';
              } 
    		} else if (form.elements[i].id == "quantity") {
    			json += form.elements[i].value + ',';
    		} else {
    			json += '"' + form.elements[i].value + '",';
    		}
    	}    	
	}

	var d = new Date();
	json += '"donationDate":' + parseInt(d.getTime()/1000) + ",";
	json += '"foodbankID":' + 12 + ",";
	json += '"staffID":' + 55;
	json += "}";
	
	alert(json);
	

	const xhr = new XMLHttpRequest();
    var  x, txt = "";

    // Function is called when API returns a ready state.
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) { // True when request sent and server has returned a response. 
            if (xhr.status == 200) {
            }

            if (xhr.status == 404) {
                console.log('File or resource not found');
            }
        }
    };

    //xhr.open('GET', 'http://3.11.63.81/api/food/all/1', true);
	xhr.open('POST', 'http://3.11.63.81/api/food/add/bagel/grain/1583409876/1583409699/4/item/2/2', true);
    xhr.send();

}

